### ISSUE TITLE
Missing logo icon in title bar

### ISSUE THREAD

**Issue by svp19** [oss2019/oss2019.github.io#12]
All the static pages hosted on the site currently miss the logo icon on the title bar.[Currently the default folded-page-icon appears].

**Requirement:** Edit the head tag in each html page to include a link to [OSS Logo](https://github.com/oss2019/oss2019.github.io/blob/master/images/oss_logo.png)

Note: Some resizing through CSS might be required.

**Comment by mrswagbhinav** [comment]
Has this been fixed?
