### ISSUE TITLE
CSS issue in cards for list of project ideas

### ISSUE THREAD

**Issue by akshatkarani** [oss2019/oss2019.github.io#22]
Border from the two neighboring cards [here](https://oss2019.github.io/SoI.html) is overlapping making it look darker than the rest of the sides.

**Comment by akshatkarani** [comment]
The first bug exists even in events cards [here](https://oss2019.github.io/events.html)

**Comment by CoderSquirrel** [comment]
Hi
change your
```
.event-card {
    padding-top: 1%;
   border: 1px solid green; 
}
```

to 

```
.event-card { 
    padding: 5px;
    padding-top: 1%;
}

.event-card > div {
    border: 1px solid green;
    padding: 5px;
    height: 100%;
}

```

It will be as it:

![image](https://user-images.githubusercontent.com/6757777/57108730-9c870500-6d01-11e9-8821-53eae0ccecfa.png)

**Comment by akshatkarani** [comment]
@CoderSquirrel Thanks for looking into it, if you want to contribute feel free to create a PR for this issue.
