### ISSUE TITLE
Unnecessary scroll in Propose an idea page

### ISSUE THREAD

**Issue by sonusourav** [oss2019/oss2019.github.io#45]
**Description**
In Propose an Idea page, scroll option is unnecessarily present even though there is only one page.

**Steps to reproduce**
1. Go to OSS page.
2. Click on Propose an Idea button.
3. Observe the new page.

**Expected**
Remove the additional scroll present there.

**Comment by geekayush** [comment]
@sonusourav Can I take this up?

**Comment by sonusourav** [comment]
@geekayush Go on.
