### ISSUE TITLE
colour in the navigation bar doesn't update

### ISSUE THREAD

**Issue by akshatkarani** [oss2019/oss2019.github.io#9]
When clicked on a button on the navigation bar the color of that button doesn't change. Currently the `Home`  is highlighted always.

**Comment by akshatkarani** [comment]
cc @svp19, do you want to fix it or let someone else pick it up.

**Comment by svp19** [comment]
@akshatkarani  Thanks for pointing this out. Lets keep this issue open for first-time contributors

**Comment by NeuralFlux** [comment]
:disappointed: I just fixed it and saw this

**Comment by svp19** [comment]
Its fine you can close this. We'll find plenty more to fix.

**Comment by akshatkarani** [comment]
:sweat_smile: I had thought of solving this issue live in front of juniors as a demo :p

**Comment by akshatkarani** [comment]
Don't close the issue before it's fixed.

**Comment by sonusourav** [comment]
@NeuralFlux has fixed this, he said above, isn't it?

**Comment by NeuralFlux** [comment]
Haven't merged the PR yet, waiting for everyone to fill the template

**Comment by AdityaSrivast** [comment]
@sonusourav is this issue fixed? I can see a class `active` being applied

**Comment by sonusourav** [comment]
@AdityaSrivast  This issue is fixed
